/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.bdudu_keskin_2221221003_bp2_p1;

import javax.swing.JOptionPane;

/**
 * @description kullanıcıların giriş yaptığı ekran
 * @assigment proje 1 (vize + final)
 * @author B Dudu Keskin 2221221003
 * @mail beyzadudu.keskin@stu.fsm.edu.tr
 */
public class giris_ekrani extends javax.swing.JFrame {

    static String email;
    
    /**
     * Creates new form giris_ekranı
     */
    public giris_ekrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_mail = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        btn_giris = new javax.swing.JButton();
        btn_mailSil = new javax.swing.JButton();
        btn_passwordSil = new javax.swing.JButton();
        btn_kaydol = new javax.swing.JButton();
        psw_pasword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 540));
        setResizable(false);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GİRİŞ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 36), new java.awt.Color(204, 204, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 55));
        jPanel2.setMinimumSize(new java.awt.Dimension(500, 55));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 55));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(500, 450));
        jPanel3.setMinimumSize(new java.awt.Dimension(500, 450));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 450));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_mail.setBackground(new java.awt.Color(0, 0, 102));
        lbl_mail.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbl_mail.setForeground(new java.awt.Color(0, 0, 102));
        lbl_mail.setText("E-Posta: ");
        jPanel3.add(lbl_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lbl_password.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(0, 0, 102));
        lbl_password.setText("Şifre:");
        jPanel3.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanel3.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 250, 50));

        btn_giris.setBackground(new java.awt.Color(204, 172, 241));
        btn_giris.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_giris.setForeground(new java.awt.Color(0, 0, 0));
        btn_giris.setText("Giriş Yap");
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });
        jPanel3.add(btn_giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 130, 60));

        btn_mailSil.setBackground(new java.awt.Color(204, 193, 246));
        btn_mailSil.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_mailSil.setForeground(new java.awt.Color(0, 0, 0));
        btn_mailSil.setText("sil");
        btn_mailSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mailSilActionPerformed(evt);
            }
        });
        jPanel3.add(btn_mailSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        btn_passwordSil.setBackground(new java.awt.Color(204, 193, 246));
        btn_passwordSil.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_passwordSil.setForeground(new java.awt.Color(0, 0, 0));
        btn_passwordSil.setText("sil");
        btn_passwordSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passwordSilActionPerformed(evt);
            }
        });
        jPanel3.add(btn_passwordSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        btn_kaydol.setBackground(new java.awt.Color(204, 172, 241));
        btn_kaydol.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_kaydol.setForeground(new java.awt.Color(0, 0, 0));
        btn_kaydol.setText("Kaydol");
        btn_kaydol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydolActionPerformed(evt);
            }
        });
        jPanel3.add(btn_kaydol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 130, 60));
        jPanel3.add(psw_pasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed


        //ceo, müdür, asistan, işçi
        email = txt_mail.getText();
        String password = psw_pasword.getText();
        Personel person = SirketDB.giris(email, password);

        if (email.isEmpty()|| password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "giriş bilgilerini doldurunuz");

        } else {
            if (person != null) {
                
                JOptionPane.showMessageDialog(this, "Basarili");
                if (person.rutbe.compareTo("ceo") == 0 || person.rutbe.compareTo("müdür") == 0) {
                    yonetici_erisim pnl_yönetici = new yonetici_erisim();
                    pnl_yönetici.setVisible(true);
                    this.dispose();
                    
                } else if (person.rutbe.compareTo("asistan") == 0 || person.rutbe.compareTo("isci") == 0) {
                    
                    calisan_bilgi_goruntuleme pnl_calisan = new calisan_bilgi_goruntuleme();
                    pnl_calisan.setVisible(true);
                    this.dispose();
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "kayıtlı olmayan bilgiler girdiniz. Kayıt olun ya da bilgilerinizi kontrol edin");
            }

        } 
    }//GEN-LAST:event_btn_girisActionPerformed

    private void btn_kaydolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydolActionPerformed
        // TODO add your handling code here:
        
        kayit_ekrani kayit = new kayit_ekrani();
        kayit.setVisible(true);
        
        this.dispose();
       
    }//GEN-LAST:event_btn_kaydolActionPerformed

    private void btn_mailSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mailSilActionPerformed

        txt_mail.setText("");

    }//GEN-LAST:event_btn_mailSilActionPerformed

    private void btn_passwordSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passwordSilActionPerformed

        
        psw_pasword.setText("");

    }//GEN-LAST:event_btn_passwordSilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giris_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giris_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_giris;
    private javax.swing.JButton btn_kaydol;
    private javax.swing.JButton btn_mailSil;
    private javax.swing.JButton btn_passwordSil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JPasswordField psw_pasword;
    private javax.swing.JTextField txt_mail;
    // End of variables declaration//GEN-END:variables
}
