/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.bdudu_keskin_2221221003_bp2_p1;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * @description yğneticilerin çalışanlara görev atayabildiği ve onların görev-görev durumlarını takip edebildiği ekran
 * @assigment proje 1 (vize + final)
 * @author B Dudu Keskin 2221221003
 * @mail beyzadudu.keskin@stu.fsm.edu.tr
 */
public class yonetici_gorev_ver extends javax.swing.JFrame {

    
    DefaultTableModel tbl_adminGorev;
    private JTable table;
    /**
     * Creates new form yonetici_erisim_calisan
     */
    public yonetici_gorev_ver() {
        initComponents();
        
        
        tbl_adminGorev = new DefaultTableModel(){
            
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        
        tbl_adminGorev.setColumnIdentifiers(new Object[]{"ISIM", "SOYISIM", "EPOSTA", "GOREV", "DURUM"});
        tbl_gorev.setModel(tbl_adminGorev);
        tabloyaBilgiYazdir();
    }
    
    
    
    
    
    
    
    private void tabloyaBilgiYazdir() {
        
        ArrayList<Calisan> calisanlar = SirketDB.calisanGorevYazdir();
        tbl_adminGorev.setRowCount(0);
        for (Calisan calisan : calisanlar) {
            tbl_adminGorev.addRow(new Object[]{calisan.isim, calisan.soyisim, calisan.eposta,calisan.gorev, calisan.durum});

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_maas = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_gorev = new javax.swing.JTable();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        lbl_soyisim = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        lbl_mail = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        lbl_work = new javax.swing.JLabel();
        cmbx_work = new javax.swing.JComboBox<>();
        btn_work = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        lbl_work1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_geri = new javax.swing.JMenu();
        menu_cıkıs = new javax.swing.JMenu();

        lbl_maas.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbl_maas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_maas.setText("Maaş");
        lbl_maas.setToolTipText("");

        txt_salary.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_gorev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_gorev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_gorevMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_gorev);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 350));

        lbl_name.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("İsim");
        jPanel1.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        txt_name.setBackground(new java.awt.Color(255, 255, 255));
        txt_name.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txt_name.setForeground(new java.awt.Color(0, 0, 0));
        txt_name.setEnabled(false);
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 160, 40));

        lbl_soyisim.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbl_soyisim.setForeground(new java.awt.Color(255, 255, 255));
        lbl_soyisim.setText("Soyisim");
        jPanel1.add(lbl_soyisim, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        txt_surname.setBackground(new java.awt.Color(255, 255, 255));
        txt_surname.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txt_surname.setForeground(new java.awt.Color(0, 0, 0));
        txt_surname.setEnabled(false);
        jPanel1.add(txt_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 160, 40));

        lbl_mail.setBackground(new java.awt.Color(0, 0, 0));
        lbl_mail.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbl_mail.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mail.setText("E-Posta");
        jPanel1.add(lbl_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        txt_mail.setBackground(new java.awt.Color(255, 255, 255));
        txt_mail.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txt_mail.setForeground(new java.awt.Color(0, 0, 0));
        txt_mail.setEnabled(false);
        jPanel1.add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 160, 40));

        lbl_work.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbl_work.setForeground(new java.awt.Color(255, 255, 255));
        lbl_work.setText("Görev");
        lbl_work.setToolTipText("");
        jPanel1.add(lbl_work, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        cmbx_work.setBackground(new java.awt.Color(0, 43, 110));
        cmbx_work.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cmbx_work.setForeground(new java.awt.Color(255, 255, 255));
        cmbx_work.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tasarım", "yorumlama", "revize" }));
        jPanel1.add(cmbx_work, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 160, 40));

        btn_work.setBackground(new java.awt.Color(204, 204, 255));
        btn_work.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_work.setForeground(new java.awt.Color(0, 0, 0));
        btn_work.setText("görev ver");
        btn_work.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_workActionPerformed(evt);
            }
        });
        jPanel1.add(btn_work, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 160, 40));

        btn_refresh.setBackground(new java.awt.Color(204, 204, 255));
        btn_refresh.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(0, 0, 0));
        btn_refresh.setText("Yenile");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 110, 40));

        lbl_work1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_work1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_work1.setText("calisan bilgilerini yazdır");
        lbl_work1.setToolTipText("");
        lbl_work1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_work1MouseClicked(evt);
            }
        });
        jPanel1.add(lbl_work1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        menu_geri.setText("geri dön");
        menu_geri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_geriMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_geri);

        menu_cıkıs.setText("çıkış yap");
        menu_cıkıs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_cıkısMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_cıkıs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    
    
    
    
    private void tbl_gorevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_gorevMouseClicked
        // TODO add your handling code here:

        int r = tbl_gorev.getSelectedRow();

        if(r == -1)
        return;

        String name = (String) tbl_gorev.getValueAt(r, 0);
        txt_name.setText(name);

        String surname = (String) tbl_gorev.getValueAt(r, 1);
        txt_surname.setText(surname);
        
        String email = (String) tbl_gorev.getValueAt(r, 2);
        txt_mail.setText(email);

        String gorev = (String) tbl_gorev.getValueAt(r, 3);
        cmbx_work.setSelectedItem(gorev);

    }//GEN-LAST:event_tbl_gorevMouseClicked

    
    
    
    
    
    
    
    
    private void menu_geriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_geriMouseClicked

        yonetici_erisim pnl_yönetici = new yonetici_erisim();
        pnl_yönetici.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_menu_geriMouseClicked

    
    
    
    
    
    
    
    
    private void menu_cıkısMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_cıkısMouseClicked
        // TODO add your handling code here:
        
        giris_ekrani giris = new giris_ekrani();
        giris.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_menu_cıkısMouseClicked

    
    
    
    
    
    
    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:

        txt_mail.setText("");
        txt_name.setText("");
        txt_salary.setText("");
        txt_surname.setText("");
        cmbx_work.setSelectedIndex(0);

        tabloyaBilgiYazdir();
    }//GEN-LAST:event_btn_refreshActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void btn_workActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_workActionPerformed
        
        Calisan np1 = new Calisan();
        
        np1.gorev = cmbx_work.getSelectedItem().toString();
        np1.eposta = txt_mail.getText();
        
        
        if(txt_mail.getText().isBlank())
            JOptionPane.showMessageDialog(rootPane, "gorev vermek için tablodan çalışan seçin");
        
        
        else if (SirketDB.gorevDuzenle(np1)) {

            JOptionPane.showMessageDialog(rootPane, "gorev verildi");
            np1.durum = "verildi";

            tabloyaBilgiYazdir();
            btn_refreshActionPerformed(evt);

        } else {
            JOptionPane.showMessageDialog(rootPane, "sorun oluştu, lütfen tekrar deneyin");
        }
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btn_workActionPerformed

    private void lbl_work1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_work1MouseClicked
        // TODO add your handling code here:
        
        info_export export = new info_export();
        
        export.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_lbl_work1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yonetici_gorev_ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yonetici_gorev_ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yonetici_gorev_ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yonetici_gorev_ver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yonetici_gorev_ver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_work;
    private javax.swing.JComboBox<String> cmbx_work;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_maas;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_soyisim;
    private javax.swing.JLabel lbl_work;
    private javax.swing.JLabel lbl_work1;
    private javax.swing.JMenu menu_cıkıs;
    private javax.swing.JMenu menu_geri;
    private javax.swing.JTable tbl_gorev;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
}
