/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fsm.bdudu_keskin_2221221003_bp2_p1;

import static com.fsm.bdudu_keskin_2221221003_bp2_p1.giris_ekrani.email;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * @description çalışanların sadece kendi bilgilerini görüntüleyip düzenleyebildikleri frame
 * @assigment proje 1 (vize + final)
 * @author B Dudu Keskin 2221221003
 * @mail beyzadudu.keskin@stu.fsm.edu.tr
 */
public class calisan_bilgi_degisim extends javax.swing.JFrame {
    
    DefaultTableModel tbl_calisanEdit;
    private JTable table;
    
    /**
     * Creates new form calisan_bilgi_talep
     */
    public calisan_bilgi_degisim() {
        initComponents();
        
        
        String arama = giris_ekrani.email;

        ArrayList<Calisan> aratmaListe = SirketDB.Aratma(arama);

        for (Calisan np1 : aratmaListe) {

            lbl_cinsiyet.setText(np1.cinsiyet);
            lbl_isim.setText(np1.isim);
            lbl_soyisim.setText(np1.soyisim);
            lbl_cinsiyet.setText(np1.cinsiyet);
        }
        
        
        
        
        lbl_email.setText(giris_ekrani.email);
        lbl_email.setEnabled(false);
        
        tbl_calisanEdit = new DefaultTableModel(){
            
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        tbl_calisanEdit.setColumnIdentifiers(new Object[]{"ISIM", "SOYISIM", "CINSIYET", "EPOSTA"});
        tbl_edit.setModel(tbl_calisanEdit);
        tabloyaBilgiYazdir();
    }
    
    
    
    
    private void tabloyaBilgiYazdir() {
        
        ArrayList<Calisan> calisanlar = SirketDB.calisanBilgiYazdir();
        tbl_calisanEdit.setRowCount(0);
        for (Calisan calisan : calisanlar) {
            tbl_calisanEdit.addRow(new Object[]{calisan.isim, calisan.soyisim, calisan.cinsiyet, calisan.eposta,});

        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_cinsiyet = new javax.swing.JLabel();
        lbl_isim = new javax.swing.JLabel();
        lbl_soyisim = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        txt_surname = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        cmbx_gender = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_edit = new javax.swing.JTable();
        lbl_kontrol = new javax.swing.JLabel();
        ptxt_sifre = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_geri = new javax.swing.JMenu();
        menu_cıkıs = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_cinsiyet.setBackground(new java.awt.Color(255, 255, 255));
        lbl_cinsiyet.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_cinsiyet.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cinsiyet.setText("cinsiyet");
        jPanel1.add(lbl_cinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 40));

        lbl_isim.setBackground(new java.awt.Color(255, 255, 255));
        lbl_isim.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_isim.setForeground(new java.awt.Color(255, 255, 255));
        lbl_isim.setText("isim");
        jPanel1.add(lbl_isim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 40));

        lbl_soyisim.setBackground(new java.awt.Color(255, 255, 255));
        lbl_soyisim.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_soyisim.setForeground(new java.awt.Color(255, 255, 255));
        lbl_soyisim.setText("soyisim");
        jPanel1.add(lbl_soyisim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 40));

        lbl_email.setBackground(new java.awt.Color(255, 255, 255));
        lbl_email.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setText("e mail");
        jPanel1.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Düzenleme için yeni bilgilerinizi giriniz:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 360, 50));

        btn_save.setBackground(new java.awt.Color(204, 204, 255));
        btn_save.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(0, 0, 0));
        btn_save.setText("kaydet");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 160, 40));

        txt_surname.setText("yeni bilgi");
        jPanel1.add(txt_surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 160, 40));

        txt_name.setText("yeni bilgi");
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 160, 40));

        cmbx_gender.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cmbx_gender.setForeground(new java.awt.Color(0, 0, 0));
        cmbx_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kadın", "erkek", "diğer" }));
        jPanel1.add(cmbx_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 160, 40));

        tbl_edit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_editMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_edit);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 320));

        lbl_kontrol.setBackground(new java.awt.Color(255, 255, 255));
        lbl_kontrol.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_kontrol.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kontrol.setText("onay için sifrenizi giriniz");
        jPanel1.add(lbl_kontrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 180, 40));
        jPanel1.add(ptxt_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 160, 40));

        getContentPane().add(jPanel1);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        menu_geri.setText("geri dön");
        menu_geri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_geriMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_geri);

        menu_cıkıs.setText("çıkış yap");
        menu_cıkıs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_cıkısMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_cıkıs);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        
        /*eğer çalışan bilgilerini değiştirmek icin buttona tıklayıp save derse ve şifre alanı boşsa öncesinde şifre girmesi için uyarı verdim.
          şifre alanı doluysa şifre ve emaili veri tabanında aratarak bunları şifrenin doğru olup olmadığını kontrol ettirdim.
          böyle bir kullanıcı varsa text fieldları kontrol ederek boş olmadıklarından emin oldum
          her ister sağlanıyorsa kişinin bilgilerini updateledim 
        */        
        Calisan np1 = new Calisan();
        
        np1.cinsiyet = (String)cmbx_gender.getSelectedItem();
        np1.isim = txt_name.getText();
        np1.soyisim = txt_surname.getText();
        
        lbl_email.setText(email);
        
        String password = ptxt_sifre.getText();
        Personel person = SirketDB.giris(lbl_email.getText(), password);

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "onay için lütfen şifrenizi girinzi");

        } else {
            
            if(person != null){
                
                JOptionPane.showMessageDialog(rootPane, "bilgiler doğru");
                
                if(txt_name.getText().equals("yeni bilgi") && txt_surname.getText().equals("yeni bilgi")){
                    
                    tabloyaBilgiYazdir();
                    ptxt_sifre.setText("");
                    JOptionPane.showMessageDialog(rootPane, "düzenleme için lütfen tüm bilgileri doldurunuz");
                   
                } else{
                    
                    JOptionPane.showMessageDialog(rootPane, "düzenleme başarılı");
                    np1.isim = txt_name.getText();
                    np1.soyisim = txt_surname.getText();
                    np1.cinsiyet = (String) cmbx_gender.getSelectedItem();
                    np1.eposta = lbl_email.getText();
                    SirketDB.calisanDüzenle(np1);
                    tabloyaBilgiYazdir();
                    ptxt_sifre.setText("");
                }
            } else
                JOptionPane.showMessageDialog(rootPane, "sifrenizi kontrol edin");
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    
    
    
    
    
    private void menu_geriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_geriMouseClicked
        // TODO add your handling code here:
        
        calisan_bilgi_goruntuleme goruntuleme = new calisan_bilgi_goruntuleme();
        goruntuleme.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_menu_geriMouseClicked

    private void menu_cıkısMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_cıkısMouseClicked
        // TODO add your handling code here:
        
        giris_ekrani giris = new giris_ekrani();
        giris.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_cıkısMouseClicked

    private void tbl_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_editMouseClicked
        // TODO add your handling code here:

        int r = tbl_edit.getSelectedRow();

        if(r == -1)
        return;

        String name = (String) tbl_edit.getValueAt(r, 0);
        txt_name.setText(name);
        lbl_isim.setText(name);

        String surname = (String) tbl_edit.getValueAt(r, 1);
        txt_surname.setText(surname);
        lbl_soyisim.setText(surname);

        String gender = (String) tbl_edit.getValueAt(r, 2);
        cmbx_gender.setSelectedItem(gender);
        lbl_cinsiyet.setText(gender);

        //String email = (String) tbl_edit.getValueAt(r, 3);
        //lbl_email.setText(email);
    }//GEN-LAST:event_tbl_editMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calisan_bilgi_degisim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calisan_bilgi_degisim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calisan_bilgi_degisim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calisan_bilgi_degisim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calisan_bilgi_degisim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmbx_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_cinsiyet;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_isim;
    private javax.swing.JLabel lbl_kontrol;
    private javax.swing.JLabel lbl_soyisim;
    private javax.swing.JMenu menu_cıkıs;
    private javax.swing.JMenu menu_geri;
    private javax.swing.JPasswordField ptxt_sifre;
    private javax.swing.JTable tbl_edit;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
}
