/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template



 */
package com.fsm.bdudu_keskin_2221221003_bp2_p1;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 * @description kullanıcıların sisteme kaydolduğu ekran
 * @assigment proje 1 (vize + final)
 * @author B Dudu Keskin 2221221003
 * @mail beyzadudu.keskin@stu.fsm.edu.tr
 */
public class kayit_ekrani extends javax.swing.JFrame {

    
    giris_ekrani giris = new giris_ekrani();
    
    
    /**
     * Creates new form Soru1Layer
     */
    
    ArrayList<Personel> personels;

    public kayit_ekrani() {
        initComponents();

        this.personels = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lbl_soyisim = new javax.swing.JLabel();
        txt_kayitSoyisim = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl_mail = new javax.swing.JLabel();
        txt_ePosta = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txt_kayitİsim = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_password = new javax.swing.JLabel();
        txtp_kayitSifreTekrar = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        cmbx_position = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbx_gender = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_phone = new javax.swing.JLabel();
        txtp_kayitSifre = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btn_giris = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btn_mailSil = new javax.swing.JButton();
        btn_kayitOl = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btn_mailSil2 = new javax.swing.JButton();
        btn_temizle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 106, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 0, 102));
        jPanel8.setMaximumSize(new java.awt.Dimension(330, 70));
        jPanel8.setMinimumSize(new java.awt.Dimension(330, 70));
        jPanel8.setPreferredSize(new java.awt.Dimension(330, 70));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_soyisim.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_soyisim.setForeground(new java.awt.Color(255, 255, 255));
        lbl_soyisim.setText("Soyisim");
        jPanel8.add(lbl_soyisim, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txt_kayitSoyisim.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel8.add(txt_kayitSoyisim, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, 40));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setMaximumSize(new java.awt.Dimension(330, 70));
        jPanel3.setMinimumSize(new java.awt.Dimension(330, 70));
        jPanel3.setPreferredSize(new java.awt.Dimension(330, 70));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_mail.setBackground(new java.awt.Color(0, 0, 0));
        lbl_mail.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_mail.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mail.setText("E-Posta");
        jPanel3.add(lbl_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txt_ePosta.setMaximumSize(new java.awt.Dimension(100, 30));
        txt_ePosta.setMinimumSize(new java.awt.Dimension(100, 30));
        txt_ePosta.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(txt_ePosta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(330, 70));
        jPanel4.setMinimumSize(new java.awt.Dimension(330, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(330, 70));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_kayitİsim.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_kayitİsim.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel4.add(txt_kayitİsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, 40));

        lbl_name.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(0, 0, 0));
        lbl_name.setText("İsim");
        jPanel4.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));
        jPanel5.setMaximumSize(new java.awt.Dimension(330, 70));
        jPanel5.setMinimumSize(new java.awt.Dimension(330, 70));
        jPanel5.setPreferredSize(new java.awt.Dimension(330, 70));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_password.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 255, 255));
        lbl_password.setText("Şifre Tekrar");
        jPanel5.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtp_kayitSifreTekrar.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.add(txtp_kayitSifreTekrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setMaximumSize(new java.awt.Dimension(330, 70));
        jPanel7.setMinimumSize(new java.awt.Dimension(330, 70));
        jPanel7.setPreferredSize(new java.awt.Dimension(330, 70));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbx_position.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cmbx_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ceo", "müdür", "asistan", "isci" }));
        jPanel7.add(cmbx_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Rütbe Seçiniz");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        cmbx_gender.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cmbx_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kadın", "erkek", "diğer" }));
        jPanel7.add(cmbx_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cinsiyet Seçiniz");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(330, 70));
        jPanel6.setMinimumSize(new java.awt.Dimension(330, 70));
        jPanel6.setPreferredSize(new java.awt.Dimension(330, 70));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_phone.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_phone.setForeground(new java.awt.Color(0, 0, 0));
        lbl_phone.setText("Şifre");
        lbl_phone.setToolTipText("");
        jPanel6.add(lbl_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtp_kayitSifre.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel6.add(txtp_kayitSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, 40));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 172, 241));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(90, 210));
        jPanel2.setMinimumSize(new java.awt.Dimension(90, 210));
        jPanel2.setPreferredSize(new java.awt.Dimension(90, 210));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_giris.setBackground(new java.awt.Color(204, 193, 246));
        btn_giris.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_giris.setForeground(new java.awt.Color(0, 0, 0));
        btn_giris.setText("giriş yapın");
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });
        jPanel2.add(btn_giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("hesabınız");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("var mı?");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 120, 140));

        jPanel9.setBackground(new java.awt.Color(204, 172, 241));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setForeground(new java.awt.Color(204, 204, 255));
        jPanel9.setMaximumSize(new java.awt.Dimension(120, 140));
        jPanel9.setMinimumSize(new java.awt.Dimension(120, 140));
        jPanel9.setPreferredSize(new java.awt.Dimension(120, 140));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_mailSil.setBackground(new java.awt.Color(204, 193, 246));
        btn_mailSil.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_mailSil.setForeground(new java.awt.Color(0, 0, 0));
        btn_mailSil.setText("sil");
        jPanel9.add(btn_mailSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        btn_kayitOl.setBackground(new java.awt.Color(204, 193, 246));
        btn_kayitOl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_kayitOl.setForeground(new java.awt.Color(0, 0, 0));
        btn_kayitOl.setText("kayıt ol");
        btn_kayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitOlActionPerformed(evt);
            }
        });
        jPanel9.add(btn_kayitOl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 120, 140));

        jPanel10.setBackground(new java.awt.Color(204, 172, 241));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setForeground(new java.awt.Color(204, 204, 255));
        jPanel10.setMaximumSize(new java.awt.Dimension(90, 210));
        jPanel10.setMinimumSize(new java.awt.Dimension(90, 210));
        jPanel10.setPreferredSize(new java.awt.Dimension(90, 210));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_mailSil2.setBackground(new java.awt.Color(204, 193, 246));
        btn_mailSil2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btn_mailSil2.setForeground(new java.awt.Color(0, 0, 0));
        btn_mailSil2.setText("sil");
        jPanel10.add(btn_mailSil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        btn_temizle.setBackground(new java.awt.Color(204, 193, 246));
        btn_temizle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_temizle.setForeground(new java.awt.Color(0, 0, 0));
        btn_temizle.setText("temizle");
        btn_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_temizleActionPerformed(evt);
            }
        });
        jPanel10.add(btn_temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 120, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitOlActionPerformed


        Personel np1 = new Personel();
        
        
        String sifre = String.valueOf(txtp_kayitSifre.getPassword());
        String sifreTekrar = String.valueOf(txtp_kayitSifreTekrar.getPassword());
         
        
        String[] regexPatternİsim = {"(([A-Z]{1}+[a-zA-Z]{1,})||([A-Z]{1}+[a-zA-Z]{1,}$)+\\s+([A-Z]{1}+[a-zA-Z]{1,})$)"};
        String[] regexPatternSoyisim = {"(([A-Z]{1}+[a-zA-Z]{1,})$)"};
        String[] regexPatternMail = {"^([a-z]+\\w*){3,}@{1}((gmail)|(hotmail)){1}(.com){1}$"};
        String[] regexPatternSifre = {"^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*\\\\-\\\\=+∫,#;(Ω≤≥]).{8,}$"};
        
        String[] patternKontrolİsim = {txt_kayitİsim.getText()};
        String[] patternKontrolSoyisim = {txt_kayitSoyisim.getText()};
        String[] patternKontrolSifre = {txtp_kayitSifre.getText()};
        String[] patternKontrolMail = {txt_ePosta.getText()};
        
        
        boolean isValid = true;
        
        
        if(!sifre.equals(sifreTekrar)){
            isValid=false;
            JOptionPane.showMessageDialog(rootPane, "şifreler eşleşmiyor");
        }
        
        
        if (SirketDB.emailKullanim(txt_ePosta.getText())) {
            isValid=false;
            JOptionPane.showMessageDialog(this, "Bu e-posta kullanımda");
        }
        
        for (int i = 0; i < regexPatternİsim.length; i++) {
            Pattern pattern = Pattern.compile(regexPatternİsim[i]);
            Matcher matcher = pattern.matcher(patternKontrolİsim[i]);
            
            if (!matcher.find()){
                isValid = false;
                JOptionPane.showMessageDialog(rootPane, "en az 2 karakterli ve büyük harfle başlayan bir isim giriniz");
            }
        } 
        
        for (int i = 0; i < regexPatternSoyisim.length; i++) {
            Pattern pattern = Pattern.compile(regexPatternSoyisim[i]);
            Matcher matcher = pattern.matcher(patternKontrolSoyisim[i]);
            
            if (!matcher.find()){
                isValid = false;
                JOptionPane.showMessageDialog(rootPane, "en az 2 karakterli ve büyük harfle başlayan bir soyisim giriniz");
            }
        }
        
        for (int i = 0; i < regexPatternMail.length; i++) {
            Pattern pattern = Pattern.compile(regexPatternMail[i]);
            Matcher matcher = pattern.matcher(patternKontrolMail[i]);
            
            if (!matcher.find()){
                isValid = false;
                JOptionPane.showMessageDialog(rootPane, "mail adresinizi (...)@hotmail.com YA DA (...)@gmail.com formatına uyacak şekilde giriniz");
            }
        }
        
        for (int i = 0; i < regexPatternSifre.length; i++) {
            Pattern pattern = Pattern.compile(regexPatternSifre[i]);
            Matcher matcher = pattern.matcher(patternKontrolSifre[i]);
            
            if (!matcher.find()){
                isValid = false;
                JOptionPane.showMessageDialog(rootPane, "en az 8 haneli olacak şekilde ve en az 1 tane büyük harf, 1 tane küçük harf ve 1 tane de işaret içeren bir şifre giriniz");
            }
        }

        if (isValid) {

            np1.isim = txt_kayitİsim.getText();
            np1.soyisim = txt_kayitSoyisim.getText();
            np1.eposta = txt_ePosta.getText();
            np1.sifre = txtp_kayitSifreTekrar.getText();
            np1.cinsiyet = cmbx_gender.getSelectedItem().toString();
            np1.rutbe = cmbx_position.getSelectedItem().toString();

            if ((np1.rutbe.compareTo("ceo") == 0 || np1.rutbe.compareTo("müdür") == 0) && SirketDB.personel_ekle(np1) ) {
                JOptionPane.showMessageDialog(rootPane, "kişi başarıyla eklendi");

                giris.setVisible(true);
                this.dispose();
                
            }else if (SirketDB.calisan_ekle(np1) &&/* SirketDB.personel_ekle(np1) &&*/ np1.rutbe.compareTo("asistan") == 0 || np1.rutbe.compareTo("isci") == 0) {
                JOptionPane.showMessageDialog(rootPane, "kişi başarıyla eklendi");

                giris.setVisible(true);
                this.dispose();
                
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "kişi eklenemedi, bilgilerinizi istenen formatta doldurduğunuza emin olun");
            }
        }


    }//GEN-LAST:event_btn_kayitOlActionPerformed

    private void btn_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_temizleActionPerformed

        txt_ePosta.setText("");
        txt_kayitİsim.setText("");
        txt_kayitSoyisim.setText("");
        txtp_kayitSifre.setText("");
        txtp_kayitSifreTekrar.setText("");

    }//GEN-LAST:event_btn_temizleActionPerformed

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed

        giris.setVisible(true);

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_girisActionPerformed

    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayit_ekrani.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayit_ekrani.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayit_ekrani.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayit_ekrani.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayit_ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_giris;
    private javax.swing.JButton btn_kayitOl;
    private javax.swing.JButton btn_mailSil;
    private javax.swing.JButton btn_mailSil2;
    private javax.swing.JButton btn_temizle;
    private javax.swing.JComboBox<String> cmbx_gender;
    private javax.swing.JComboBox<String> cmbx_position;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_soyisim;
    private javax.swing.JTextField txt_ePosta;
    private javax.swing.JFormattedTextField txt_kayitSoyisim;
    private javax.swing.JTextField txt_kayitİsim;
    private javax.swing.JPasswordField txtp_kayitSifre;
    private javax.swing.JPasswordField txtp_kayitSifreTekrar;
    // End of variables declaration//GEN-END:variables
}
